codepay_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from api import viewsets



urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'/', include('core.urls', namespace='core')),
    path(r'accounts/', include('django.contrib.auth.urls')),
    path(r'api/rpa', viewsets.payment_get, name='payment-get'),
    path(r'api/rpa/<str:status>', viewsets.payment_get, name='payment-filter'),
    path(r'api/rpa/resquest/<str:hashid>', viewsets.payment_request, name='payment-request'),
    path(r'api/token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(r'api/token/refresh', TokenRefreshView.as_view(), name='token_refresh'),

]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/urls.py
from django.urls import path

from core import views as v

app_name = 'core'


urlpatterns = [
    path(r'/', v.index, name='index'),
    path(r'rpa/', v.rpa, name='rpa'),
    path(r'rpa_adm/', v.rpa_adm, name='rpa_adm'),
]

core/models.py
from django.db import models
from utils.models import Base
from django.contrib.auth.models import User
import uuid


class Profile(Base):
    class Meta:
        verbose_name = 'perfil'
        verbose_name_plural = 'perfis'

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'perfil do usuário {self.user}'


class Provider(Base):
    class Meta:
        verbose_name = 'fornecedor'
        verbose_name_plural = 'fornecedores'
        ordering = ['name']

    def __str__(self):
        """String for representing the Model Object"""
        return f'{self.name}'

    id_register = models.CharField('CNPJ', max_length=14, primary_key=True)
    id_user = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name='Usuario')
    name = models.CharField('Nome da Empresa', max_length=100)
    address = models.CharField('Endereço', max_length=100)
    email = models.EmailField('E-mail', max_length=100)
    phone = models.CharField('Telefone', max_length=100)
    site = models.CharField('Site', max_length=100)


class Payment(Base):
    class Meta:
        verbose_name = 'pagamento'
        verbose_name_plural = 'pagamentos'
        ordering = ['due_date']

    def __str__(self):
        """String for representing the Model Object"""
        return f'{self.id_provider.name}({self.id_payment})'

    status_choices = (
        ('disponible', 'Disponible'),
        ('not_disponible', 'Not_Disponible'),
        ('requested', 'Requested'),
        ('released', 'Released'),
        ('denied', 'Denied'),
    )

    id_payment = models.UUIDField(primary_key=True, default=uuid.uuid4)
    id_provider = models.ForeignKey(Provider, on_delete=models.CASCADE, verbose_name='Fornecedor')
    due_date = models.DateField('Data de vencimento')
    original_value = models.FloatField('Valor original', max_length=30)
    new_value = models.FloatField('Novo Valor', max_length=30)
    status = models.CharField(max_length=14, choices=status_choices, default='disponible')
    doc_number = models.CharField('Numero do Boleto', max_length=255, null=True, blank=True)


class PaymentLog(Base):
    class Meta:
        verbose_name = 'log de pagamento'
        verbose_name_plural = 'logs de pagamentos'

    user_agent = models.ForeignKey(Profile, models.DO_NOTHING)
    status = models.CharField('Status', max_length=50)
    id_payment = models.ForeignKey(Payment, models.DO_NOTHING, related_name='logs')

utils/models.py
#!coding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


class Base(models.Model):
    """Model Base para todos os outros models do projeto."""

    class Meta:
        abstract = True

    created = models.DateTimeField('Criado em', default=timezone.now)
    updated = models.DateTimeField('Alterado em', auto_now=True)

core/forms.py
from django import forms
from core.models import Payment


class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = '__all__'

core/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render
from django.contrib.auth.mixins import PermissionRequiredMixin
from core.mixins import (persiste_mult_provider_payments_mixin,
                         persiste_payments_mixin)
from core.models import Payment, Provider


@login_required
def index(request):
    template_name = 'index.html'
    return render(request, template_name)


@login_required
def rpa(request):
    template_name = 'rpa.html'
    user = request.user
    provider = Provider.objects.get(id_user=user.pk)

    if request.method == 'POST':
        persiste_payments_mixin(user, provider, request.POST.items())

    response = {
        'object_list': Payment.objects.filter(id_provider=provider.pk)
    }
    return render(request, template_name, response)


@login_required
@permission_required('global_permissions.can_acess_all_payments')
def rpa_adm(request):
    template_name = 'rpa_adm.html'

    if request.method == 'POST':
        persiste_mult_provider_payments_mixin(request.POST.items())

    response = {
        'object_list': Payment.objects.all()
    }
    return render(request, template_name, response)

core/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Request Payment Antecipation</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }
        
        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }


    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
</head>

<body>
{% include "nav.html" %}
{% include "sidebar.html" %}

{% block content %}{% endblock content %}

<script src=".{% static 'js/bootstrap.bundle.min.js' %}"></script>

<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"
        integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js"
        integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha"
        crossorigin="anonymous"></script>
<script src="{% static 'js/dashboard.js' %}"></script>
</body>


</html>

core/templates/index.html
{% extends 'base.html' %}

{% block  content %}

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard - Bem Vindo {{ user.first_name }} !!!</h1>
    </div>


</main>

{% endblock content %}

core/templates/nav.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Company name</a>
    <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
            data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-nav">
        <div class="nav-item text-nowrap">
            <a class="nav-link px-3" href="{% url 'logout' %}">Sign out</a>
        </div>
    </div>
</header>

core/templates/rpa.html
{% extends 'base.html' %}

{% block  content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Request Payment Antecipation</h1>
    </div>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h2">Available Antecipations</h2>

    </div>
    <div class="table-responsive">
        <form action="." method="POST">
            {% csrf_token %}
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Check</th>
                    <th scope="col">Id Payment</th>
                    <th scope="col">Date</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Value</th>
                    <th scope="col">Provider</th>
                    <th scope="col">Register</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                {% if item.status == 'disponible' %}
                <tr>
                    <td><input type="checkbox" id="payment" name="payment{{ forloop.counter }}" value={{ item.id_payment}}></td>
                    <td>{{ item.id_payment }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.due_date }}</td>
                    <td>{{ item.original_value }}</td>
                    <td>{{ item.id_provider.name }}</td>
                    <td>{{ item.id_provider.pk }}</td>
                    <td>{{ item.status }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <button type="submit" class="btn btn-sm btn-outline-secondary">Request Selected Antecipation(s)</button>
        </form>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h2 class="h2">Historic The Paymants</h2>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Id Payment</th>
                    <th scope="col">Date</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Value</th>
                    <th scope="col">Provider</th>
                    <th scope="col">Register</th>
                    <th scope="col">Status</th>
                </tr>

                </thead>
                <tbody>
                {% for item in object_list %}
                {% if item.status != 'disponible' %}
                <tr>
                    <td>{{ item.id_payment }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.due_date }}</td>
                    <td>{{ item.new_value }}</td>
                    <td>{{ item.id_provider.name }}</td>
                    <td>{{ item.id_provider.pk }}</td>
                    <td>{{ item.status }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock content %}

core/templates/rpa_adm.html
{% extends 'base.html' %}

{% block  content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">Request Payment Antecipation</h1>
    </div>

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h2 class="h2">Available Antecipations</h2>

    </div>
    <div class="table-responsive">
        <form action="." method="POST">
            {% csrf_token %}
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Check</th>
                    <th scope="col">Id Payment</th>
                    <th scope="col">Date</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Value</th>
                    <th scope="col">Provider</th>
                    <th scope="col">Register</th>
                    <th scope="col">Status</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                {% if item.status == "disponible" or item.status == "requested" %}
                <tr>
                    <td><input type="checkbox" id="payment" name="payment_{{ item.id_payment }}" value={{ item.id_payment}}></td>
                    <td>{{ item.id_payment }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.due_date }}</td>
                    <td>{{ item.original_value }}</td>
                    <td>{{ item.id_provider.name }}</td>
                    <td>
                        <input type="text" id="provider" name="provider_{{ item.id_payment }}" value="{{ item.id_provider.pk }}"readonly>
                    </td>
                    <td>
                        <select class="form-select" name="status_{{ item.id_payment }}" id="status" required>
                            <option value="requested">Requested</option>
                            <option value="released">Released</option>
                            <option value="denied">Denied</option>
                            <option selected disabled value="{{ item.status }}">{{ item.status }}</option>
                        </select>
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <button type="submit" class="btn btn-sm btn-outline-secondary">Process Selected Antecipation(s)</button>
        </form>

        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            <h2 class="h2">Historic The Paymants</h2>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-sm">
                <thead>
                <tr>
                    <th scope="col">Id Payment</th>
                    <th scope="col">Date</th>
                    <th scope="col">Due Date</th>
                    <th scope="col">Value</th>
                    <th scope="col">Provider</th>
                    <th scope="col">Register</th>
                    <th scope="col">Status</th>
                </tr>

                </thead>
                <tbody>
                {% for item in object_list %}
                {% if item.status != "disponible" and item.status != "requested" %}
                <tr>
                    <td>{{ item.id_payment }}</td>
                    <td>{{ item.created }}</td>
                    <td>{{ item.due_date }}</td>
                    <td>{{ item.new_value }}</td>
                    <td>{{ item.id_provider.name }}</td>
                    <td>{{ item.id_provider.pk }}</td>
                    <td>{{ item.status }}</td>
                </tr>
                {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</main>
{% endblock content %}

core/templates/send_email/update_status.html
Prezado {{ name }},

Uma ou mais das sua solicitações de pagamento foi alterada:
Empresa : {{ employer }}
{% for linha in lista %}

Solicitação de pagamento de numero {{ linha }} o status foi alterado de {{ old_status }} para {{ to_status }}

{% endfor %}


Gentileza não responder este e-mail,

Atenciosamente,

Equipe Codepay

core/templates/sidebar.html
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">

                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'core:index' %}">
                            <span data-feather="home"></span> Dashboard
                        </a>
                    </li>
                    {% if perms.global_permissions.can_acess_all_payments %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:rpa_adm' %}">
                            <span data-feather="RPA Admin"></span> RPA Admin
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:rpa' %}">
                            <span data-feather="RPA"></span> RPA
                        </a>
                    </li>
                    {% endif %}


                </ul>
            </div>
        </nav>
    </div>
</div>